const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={step:1,zip:'',bill:165,sqft:2200,heating:'gas',orientation:'south',shade:10,roof:'normal',goal:'essential',resilience:true,lead:{name:'',email:'',phone:''},loads:{fridge:true,lights:true,wifi:true,tv:false,fans:false,microwave:false,washer:false,ac:false,heat:false},estimate:null};
const applianceData=[
{id:'fridge',n:'Refrigerator',w:180,h:8,d:'Cycling appliance'},{id:'lights',n:'LED lights',w:180,h:5,d:'Essential lighting'},{id:'wifi',n:'Wi-Fi / networking',w:35,h:12,d:'Router + modem'},{id:'tv',n:'Television',w:120,h:4,d:'Entertainment'},{id:'fans',n:'Fans',w:160,h:8,d:'Ceiling / portable'},{id:'microwave',n:'Microwave',w:1200,h:.25,d:'Short intermittent load'},{id:'washer',n:'Washer',w:500,h:.5,d:'Intermittent load'},{id:'ac',n:'Central A/C',w:3500,h:3,d:'Large variable load'},{id:'heat',n:'Electric heat / heat pump',w:4500,h:3,d:'Large variable load'}];
const products=[
{id:'enphase',name:'Enphase IQ Battery 10C',cap:'10.08 kWh',power:'7.08 kW',rebate:1000,low:9000,high:12000,desc:'AC-coupled storage for homes using Enphase IQ8 solar.'},
{id:'tesla',name:'Tesla Powerwall 3',cap:'13.5 kWh',power:'11.5 kW',rebate:2000,low:11500,high:14500,desc:'Integrated solar inverter with high continuous backup power.'},
{id:'sigenergy',name:'Sigenergy PointGuard / SigenStor',cap:'5–20 kWh',power:'Up to 12 kW*',rebate:2000,low:8500,high:14000,desc:'Scalable storage platform installed by Elite Electric in Utah.'}];
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function setText(id,v){const e=$('#'+id);if(e)e.textContent=v}
function renderLoads(){const box=$('#appliances');box.innerHTML=applianceData.map(a=>`<label class="appliance"><input type="checkbox" data-load="${a.id}" ${S.loads[a.id]?'checked':''}><span><b>${a.n}</b><small>${a.w.toLocaleString()} W · ${a.d}</small></span></label>`).join('');$$('[data-load]').forEach(x=>x.onchange=()=>{S.loads[x.dataset.load]=x.checked;calculate()});}
function loadCalc(){let w=0,d=0;applianceData.forEach(a=>{if(S.loads[a.id]){w+=a.w;d+=a.w*a.h/1000}});return{k:w/1000,w,d}}
function calculate(){
 S.bill=clamp(Number($('#bill')?.value)||165,50,2500);S.sqft=clamp(Number($('#sqft')?.value)||2200,500,15000);S.shade=clamp(Number($('#shade')?.value)||0,0,35);S.heating=$('#heating')?.value||'gas';S.resilience=$('#resilience')?.checked??true;
 const orient={south:1,se:.95,ew:.88,north:.68}[S.orientation],roof={normal:1,complex:.94,limited:.90}[S.roof],shade=clamp(1-S.shade/100*.72,.7,1),hf={gas:1,heatpump:1.12,electric:1.18,mixed:1.06}[S.heating];
 const sun=Math.max(500,4.8*365*orient*roof*shade),rate=.145,annualUse=Math.max(1,S.bill*12/rate*hf),target=S.resilience?.92:.86;let kw=clamp(annualUse*target/sun,3,25);if(S.sqft<1300)kw=Math.min(kw,11);if(S.sqft>4500)kw=Math.max(kw,8);const production=kw*sun,offset=clamp(production/annualUse*100,0,100),load=loadCalc();
 const min={essential:8,comfort:12,whole:18}[S.goal];let battery=Math.max(min,load.k*(S.goal==='whole'?1.35:S.goal==='comfort'?1.55:1.8));battery=Math.ceil(battery/2)*2;battery=clamp(battery,8,40);const usable=battery*.9,runtime=load.w>0?usable/load.w:0;
 const solarLow=kw*2000,solarHigh=kw*2625;let p=products.find(x=>x.id==='tesla');if(load.w<5.5&&S.goal==='essential')p=products.find(x=>x.id==='enphase');if(battery>=16||S.goal==='whole')p=products.find(x=>x.id==='sigenergy');const projectLow=solarLow+p.low,projectHigh=solarHigh+p.high,annualBill=S.bill*12,twentyFive=Math.max(0,annualBill*offset/100*25);
 S.estimate={kw,offset,production,annualBill,battery,runtime,projectLow,projectHigh,twentyFive,product:p.name,loadKw:load.k,dailyKwh:load.d,generatedAt:new Date().toISOString()};
 setText('watts',(load.w).toLocaleString()+' W');setText('daily',load.d.toFixed(1)+' kWh');setText('battery',battery+' kWh');setText('rKw',kw.toFixed(1)+' kW');setText('rOffset',Math.round(offset)+'%');setText('rBattery',battery+' kWh');setText('rProduction',Math.round(production).toLocaleString());setText('rAnnual',money(annualBill));setText('rRuntime',runtime.toFixed(1)+' hrs');setText('rPrice',money(projectLow)+'–'+money(projectHigh));setText('savings25',money(twentyFive));setText('savingsText',`Based on the modeled ${Math.round(offset)}% annual energy offset and the current planning assumptions, this is an illustrative 25-year view—not a guaranteed utility bill savings figure.`);setText('rebatePill',`RMP rebate: up to ${money(p.rebate)} shown in current planning data; verify eligibility`);
 const pb=$('#products');if(pb)pb.innerHTML=products.map(x=>`<div class="product"><strong>${x.name} · ${x.cap} · ${x.power}</strong><small>${x.desc} Planning range: ${money(x.low)}–${money(x.high)}. RMP rebate shown in the calculator: ${money(x.rebate)}; eligibility and current program rules must be verified.</small></div>`).join('');
 const notes=[`Modeled annual production is about ${Math.round(production).toLocaleString()} kWh.`,`The ${Math.round(offset)}% figure is an energy-offset model, not a promise of a ${Math.round(offset)}% bill reduction.`,`Backup runtime assumes the selected loads run at their planning wattages and does not predict actual appliance cycling.`,`Final design depends on the property, utility rules, equipment availability and site assessment.`];const ul=$('#notes');if(ul)ul.innerHTML=notes.map(n=>`<li>${n}</li>`).join('');
 setText('leadSummary',kw.toFixed(1)+' kW · '+Math.round(offset)+'% offset');setText('leadBattery',battery+' kWh');setText('leadZip',S.zip||'—');updateStepUI();
}
function validateContact(){const name=$('#leadName').value.trim(),email=$('#leadEmail').value.trim(),phone=$('#leadPhone').value.trim(),zip=$('#zip').value.trim();if(name.length<2)return 'Please enter your name.';if(!/^\S+@\S+\.\S+$/.test(email))return 'Please enter a valid email.';if(phone.replace(/\D/g,'').length<7)return 'Please enter a valid phone number.';if(!/^\d{5}$/.test(zip))return 'Please enter a 5-digit Utah ZIP code.';S.lead={name,email,phone};S.zip=zip;return ''}
async function saveLead(){const err=validateContact();const status=$('#saveLeadStatus');if(err){status.textContent=err;status.className='status-error';return false}calculate();status.textContent='';try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:S.lead.name,email:S.lead.email,phone:S.lead.phone,zip:S.zip,data:{calculator:{bill:S.bill,sqft:S.sqft,heating:S.heating,orientation:S.orientation,shade:S.shade,roof:S.roof,goal:S.goal,resilience:S.resilience,loads:S.loads},estimate:S.estimate}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to save');status.textContent='';status.className='status-ok';return true}catch(e){status.textContent='';status.className='status-error';console.warn('Lead save:',e);return false}}
function updateStepUI(){setText('stepText',S.step+' / 5');setText('stepPct',Math.round(S.step/5*100)+'%');const fill=$('#barFill');if(fill)fill.style.width=(S.step/5*100)+'%';$$('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===S.step));setText('liveKw',S.estimate?S.estimate.kw.toFixed(1)+' kW':'—');setText('liveOffset',S.estimate?Math.round(S.estimate.offset)+'%':'—');setText('liveBattery',S.estimate?S.estimate.battery+' kWh':'—');setText('liveLoad',S.estimate?S.estimate.loadKw.toFixed(1)+' kW':'—')}
function showStep(n){S.step=clamp(n,1,5);$$('.screen').forEach(x=>x.classList.toggle('active',Number(x.dataset.screen)===S.step));const next=$('#next'),back=$('#back');back.classList.toggle('hidden',S.step===1);next.innerHTML=S.step===5?'Start over <b>↻</b>':'Continue <b>→</b>';window.scrollTo({top:0,behavior:'smooth'});calculate();updateStepUI();sendEmbedHeight()}
function collectZip(){S.zip=$('#zip').value.trim()}
$('#orientation').querySelectorAll('.card').forEach(b=>b.onclick=()=>{$$('#orientation .card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');S.orientation=b.dataset.v;calculate()});
$('#roofArea').querySelectorAll('.card').forEach(b=>b.onclick=()=>{$$('#roofArea .card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');S.roof=b.dataset.v;calculate()});
$('#goals').querySelectorAll('.goal').forEach(b=>b.onclick=()=>{$$('#goals .goal').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');S.goal=b.dataset.v;calculate()});
$('#shade').oninput=()=>{setText('shadeLabel',$('#shade').value+'% shade');calculate()};$('#zip').oninput=collectZip;$('#bill').oninput=calculate;$('#sqft').oninput=calculate;$('#heating').onchange=calculate;$('#resilience').onchange=calculate;
$('#reset').onclick=()=>{S.loads={fridge:true,lights:true,wifi:true,tv:false,fans:false,microwave:false,washer:false,ac:false,heat:false};renderLoads();calculate()};
$('#next').onclick=async()=>{if(S.step===1){const ok=await saveLead();if(!ok)return;collectZip();}if(S.step<5)showStep(S.step+1);else location.reload()};$('#back').onclick=()=>showStep(S.step-1);
function sendEmbedHeight(){const h=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);if(parent!==window)parent.postMessage({type:'elite-electric-calculator-height',height:h},'*')}
window.addEventListener('resize',sendEmbedHeight);window.addEventListener('load',()=>{renderLoads();calculate();setTimeout(sendEmbedHeight,250);setTimeout(sendEmbedHeight,1000)});if('ResizeObserver'in window)new ResizeObserver(sendEmbedHeight).observe(document.body);
window.addEventListener('message',e=>{if(e.data?.type==='elite-lead-form-height'&&Number(e.data.height)>200){const f=$('#leadFrame');if(f)f.style.height=(Number(e.data.height)+12)+'px';sendEmbedHeight()}});
renderLoads();calculate();showStep(1);
