create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_key text unique not null,
  name text not null,
  email text not null,
  phone text not null,
  zip text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads(created_at desc);

alter table public.leads enable row level security;
-- The app's Vercel API uses the Supabase service-role key server-side.
-- No public/browser policy is created, so visitors cannot query the lead table directly.
