create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_key uuid default gen_random_uuid() unique not null,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  zip text not null,
  data jsonb not null default '{}'::jsonb
);
create index if not exists leads_created_at_idx on public.leads(created_at desc);
-- The Vercel API uses the Supabase service-role key server-side, so do not expose that key in the browser.
